### ISSUE TITLE
Unexpected list type TagEnd in BinaryTagReader

### ISSUE THREAD

**Issue by CkR-0ff** [cyotek/Cyotek.Data.Nbt#4]
Hi,
I noticed that when saving a structure with Structure Block from Minecraft (without the Entities) apparently it puts TagEnd as type for the TagList for Entities.
Every time when I try loading the nbt with NbtDocument.Load() it throws the custom exception "Unexpected list type '{listType}' found."
If i manually edit the TagList so it's type is TagCompound for example it loads normally.
Maybe there was some recent change in minecraft that changed how the entities tag was created.

**Comment by cyotek** [comment]
Hello,

Thanks for raising this issue. As `TagEnd` isn't normally a valid type that's why the library is throwing the exception. Maybe I should just ignore the type if the length is also zero as your message seems to imply.

Do you have an example of a file that the library is crashing on for me to test with? 

Regards;
Richard Moss

**Comment by CkR-0ff** [comment]
Hi,
No problem. Glad I can help. 
I used that file: 
[housegarden.zip](https://github.com/cyotek/Cyotek.Data.Nbt/files/1777805/housegarden.zip)

**Comment by cyotek** [comment]
Hello,

Thanks for the sample. I tested it, and changed the library code to only throw the exception if values have been defined. 

I've pushed a commit with the fix. However, there's no compiled binary, I had completely forgotten that for whatever reason I've been publishing the package to a private Nuget server... something else to sort out!

Thanks again for the bug report.

Regards;
Richard Moss

**Comment by CkR-0ff** [comment]
Hi,
Thanks for the quick fix. Files are loading correctly now. 
And if I may say I find your library the most comprehensive to work form the NBT libs I have tried. Thanks again for the great work.
